#!/usr/bin/env bash

set -eu
set -o pipefail

bindir=$(realpath "$(dirname "$0")")

. "$bindir"/functions.bash

USAGE="Usage: $0 env [...env]"

if [ $# = 0 ]; then
  error "$USAGE"
elif [ $# = 1 -a "$1" = -h ]; then
  info "$USAGE"
  exit 0
fi

go() {
  local env=$1
  cmd docker image tag fb-main:{latest,"$env"}
}

for env in "$@"; do
  go "$env"
done
